# Generated by Django 5.1 on 2024-10-18 01:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_passwordresettoken'),
        ('terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='historial_medico',
            new_name='descripcion_patologia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='dispositivo_ortesis',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='progreso',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='corriente',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='estado',
        ),
        migrations.AddField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.provincia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.region'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='angulo_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='angulo_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='sesion',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='velocidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='motivo_desvinculacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Corriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corriente', models.FloatField()),
                ('hora', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corriente', to='terapeuta.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='terapeuta.paciente')),
            ],
        ),
    ]
