# Generated by Django 5.1 on 2024-10-19 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0002_remove_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_final',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
