# Generated by Django 5.1 on 2024-09-29 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0002_paciente_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
