# Generated by Django 5.1 on 2024-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0003_remove_cita_hora_cita_hora_final_cita_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_terapeutas/'),
        ),
    ]
