# Generated by Django 5.1 on 2024-11-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0004_terapeuta_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.cita')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta')),
            ],
        ),
    ]
