# Generated by Django 5.1 on 2024-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0004_paciente_comuna_paciente_provincia_paciente_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='motivo_desvinculacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
