# Generated by Django 5.1 on 2024-09-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0005_alter_paciente_motivo_desvinculacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='imc',
        ),
    ]
