# Generated by Django 5.1 on 2024-11-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0005_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='provincia',
        ),
    ]
