# Generated by Django 5.1 on 2024-10-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0006_rename_direccion_paciente_calle_remove_paciente_imc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historial_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='progreso',
        ),
        migrations.AddField(
            model_name='paciente',
            name='descripcion_patologia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
