# Generated by Django 5.1 on 2024-11-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0006_remove_paciente_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20),
        ),
    ]
