# Generated by Django 5.1 on 2024-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0007_remove_paciente_historial_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='dispositivo_ortesis',
        ),
    ]
