# Generated by Django 5.1 on 2024-10-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0008_remove_paciente_dispositivo_ortesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='corriente',
        ),
        migrations.CreateModel(
            name='Corriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corriente', models.FloatField()),
                ('hora', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corriente', to='terapeuta.sesion')),
            ],
        ),
    ]
