# Generated by Django 5.1 on 2024-11-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0008_rutina_cantidad_sesiones_rutina_frecuencia_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeuta',
            name='horas_trabajadas',
        ),
        migrations.CreateModel(
            name='HorasTrabajadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('horas', models.FloatField()),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_trabajadas', to='terapeuta.terapeuta')),
            ],
            options={
                'ordering': ['-año', '-mes'],
                'unique_together': {('terapeuta', 'año', 'mes')},
            },
        ),
    ]
