# Generated by Django 5.1 on 2024-10-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0007_observacion'),
        ('terapeuta', '0014_cita_tipo_cita'),
    ]

    operations = [
    ]
