# Generated by Django 5.1 on 2024-11-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_passwordresettoken'),
        ('terapeuta', '0006_remove_paciente_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='provincia',
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.region'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
